### ISSUE TITLE
Could not initialize class io.netty.util.internal.PlatformDependent0

### ISSUE THREAD

**Issue by try-agaaain** [shaogezhu/easy-rpc#2]
遇到一个错误，gpt分析说“Java版本和Netty的版本不兼容导致的。可以尝试升级或者降级你的Netty版本，或者更改Java版本，以解决这个问题。”

```bash
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-05-03 12:53:49.931 ERROR 8282 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.shaogezhu.easy.rpc.spring.starter.config.RpcServerAutoConfiguration': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1771) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) ~[spring-boot-2.1.13.RELEASE.jar:2.1.13.RELEASE]
        at com.shaogezhu.easy.rpc.provider.springboot.ProviderApplication.main(ProviderApplication.java:14) ~[classes/:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:101) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:32) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.Signal$1.<init>(Signal.java:27) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.Signal.<clinit>(Signal.java:27) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:42) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:51) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at com.shaogezhu.easy.rpc.core.server.Server.startServerApplication(Server.java:52) ~[classes/:na]
        at com.shaogezhu.easy.rpc.spring.starter.config.RpcServerAutoConfiguration.afterPropertiesSet(RpcServerAutoConfiguration.java:52) ~[classes/:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1830) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1767) ~[spring-beans-5.1.14.RELEASE.jar:5.1.14.RELEASE]
        ... 16 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @fdc8126 [in thread "main"]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
        at io.netty.util.internal.PlatformDependent0$1.run(PlatformDependent0.java:69) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) ~[na:na]
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:64) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:939) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:956) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
        ... 32 common frames omitted

2024-05-03 12:53:49.934  INFO 8282 --- [       Thread-1] c.s.e.r.core.server.ServerShutdownHook   : server destruction
```

**Comment by try-agaaain** [comment]
尝试将Maven配置的Java编译器的版本设置为11后解决。

将所有`pom.xml`文件中的1.8改为11

```xml
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.source>1.8</maven.compiler.source>
 ```
